# model
# model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
model_name_or_path: /raid/model/save_model_llama3/Llama-3-8B-80K-SLR-Fact-Held-240513

# method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj

# ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json

# dataset
# dataset: identity,alpaca_gpt4_en
dataset: slr-catchwords
template: llama3
cutoff_len: 71680
max_samples: 8200
val_size: 0.0
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: saves/llama3-8b-it-80k/lora/sft
logging_steps: 10
save_steps: 20
save_total_limit: 50
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 0.00005
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: false
pure_bf16: true
quantization_bit: 4            # use 4-bit QLoRA
# loraplus_lr_ratio: 16.0,       # use LoRA+ algorithm with lambda=16.0
use_unsloth: true              # use UnslothAI's LoRA optimization for 2x faster training
flash_attn: fa2

# # eval
# per_device_eval_batch_size: 1
# evaluation_strategy: steps
# eval_steps: 500
